Add files via upload

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,15 +1,14 @@
-#!/usr/bin/env bash 
+#!/bin/bash 
 
-
-#      ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-#      ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-#      ▇▇          ▇ @XB_0B   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-#      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @XB_0B
-#      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @XB_0B  ▇▄                 ▇▇                 ▇▇
-#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source ZORO BY @XB_0B
+#─▄███▄──▄███▄─
+#▐████████████▌
+#─████████████─
+#──▀████████▀──
+#─────▀██▀─────
+#┊NEZAK ‿ @TH3NEK
+#┊@AAH_MD ‿ @TH3SS
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
- 
 RED='\033[0;31m'
 SMAY='\033[0;36m' 
 GREEN='\033[0;32m'
@@ -22,17 +21,18 @@ Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
 echo -e "${GREEN}
-▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-▇▇          ▇ @XB_0B   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @XB_0B
-▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @XB_0B  ▇▄                 ▇▇                 ▇▇
-▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source ZORO BY @XB
-
-----------------------------------------------------------------------${CNIL}"
+─▄███▄──▄███▄─
+▐████████████▌
+─████████████─
+──▀████████▀──
+─────▀██▀─────
+┊NEZAK ‿ @TH3NEK
+تم تطوير وبرمجة السورس من قبل علي محمد
+┊@AAH_MD ‿ @TH3SS
+ ---------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source ZORO 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Th3Neyzk 
 ${CNIL}";
 exit;
 fi
@@ -42,7 +42,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source ZORO${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source TH3NEYZK${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -57,24 +57,42 @@ echo -e "${RED}
 \n\n"
 lua ./inc/Run.lua
 exit;
-fi
-
-
-TOKEN=`cat ./inc/Token.txt`
-sudo chmod +x ./TG
-
-if [ "$1" == "R" ] ; then
-while(true) do
-killall -q ./TG
-sudo rm -fr ../.telegram-cli
-./TG -s inc/Run.lua --bot=$TOKEN
-done
 else
-
-if ! screen -list | grep -q "ZORO"; then
-screen -S ZORO ./run R
+TOKEN=`cat ./inc/Token.txt`
+BOTID=`echo $TOKEN | cut -f1 -d":"`
+Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
+if [[ $Sudo == "" ]]; then
+rm -fr ./inc/Token.txt
+lua ./inc/Run.lua
+exit;
 fi
-screen -S ZORO -X kill
-screen -S ZORO ./run R
+fi
+
+
+chmod +x ./TG  
+Loops=0
+if [ "$1" == "R" ]; then
+while [[ $Loops -le 5 ]]; do
+sleep 1s
+sudo rm -fr ~/.telegram-cli
+./TG -s ./inc/Run.lua --bot=$TOKEN
+let Plas=Loops+1
+redis-cli SETEX $TOKEN 3 $Plas
+Loops=`redis-cli GET ${TOKEN}`
+echo $Loops
+if [[ $Loops == 5 ]]; then
+curl "https://api.telegram.org/bot${TOKEN}/sendmessage" -F "chat_id=${Sudo}" -F "text=THESOURCE-Reloaded-${COUNTER}-times" &>/dev/null
+screen -X -S neyzk quit
+fi
+done
+else 
+if [[ $Loops == 0 ]]; then
+if ! screen -list | grep -q "neyzk"; then
+screen -S neyzk ./run R
+else
+screen -X -S neyzk quit
+screen -S neyzk ./run R
+fi
+fi
 fi
 
